spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/apim?currentSchema=sst
    username: apim
    password: apim
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    properties:
      hibernate:
        jdbc:
          batch_size: 500
        order_inserts: true
        order_update: true
  banner:
    location: classpath:banner-local.text
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
logging:
  config: classpath:logback.xml
application:
  rest:
    connection-request-timeout: 60000
    connect-timeout: 60000
    socket-timeout: 61000
  cluster:
    cluster-name: ssantalk-cluster-auth-local
    instance-name: ssantalk-instance-auth-local-1
    multicastPort: 55327
    basePort: 55701
    bindAddress: 127.0.0.1